### ISSUE TITLE
URLink #2 URL 비슷한 서비스 벤치마킹 및 차별점 도출

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#10]

**Comment by anxiubin** [comment]
**OneTab Plus:Tab Manage & Productivity**

- UI 깔끔
- 원탭과 비교하여 기능이 많지 않음

![sample1](https://user-images.githubusercontent.com/51507260/74848380-f503bd80-537a-11ea-919c-b70d411d1fc9.PNG)


**Tabli**

- UI 깔끔
- 원탭과 달리 새로운 탭으로 여는 것이 아니라 작은 윈도우 창으로도 열 수 있고,
  익스텐션 아이콘 클릭만 해도 열 수 있음
- 원탭은 로컬스토리지에 저장하는 것과 달리 크롬의 북마크에 새로운 폴더가 생성된다

![sample2](https://user-images.githubusercontent.com/51507260/74848402-fb923500-537a-11ea-891c-b39d06d28e54.PNG)

![screen](https://user-images.githubusercontent.com/51507260/74848340-ec12ec00-537a-11ea-8412-a4e90e6986cd.png)

**Comment by leesoo7595** [comment]
👍👍👍👍

**Comment by suath** [comment]
**<Session Buddy (별5, 리뷰/다운로드 24,245/ 887,178)>**
<img width="1126" alt="스크린샷 2020-02-20 오후 10 08 28" src="https://user-images.githubusercontent.com/48906747/74941809-08745e80-5437-11ea-83b3-426d83b21d40.png">

- current, previous, saved의 구획
- 현재 세션과, 저장하지 않은 지난 세션기록도 열람 가능
- 저장 시 원탭처럼 세션 종료되지 않음 
- 검색 가능 
——
구글 리뷰: 원탭보다 소스 덜 차지 한다고 함 
파이어폭스의 세션관리 구현했다고 칭찬

**<Toby (별4.5, 2,600/239,344)>**
<img width="1126" alt="스크린샷 2020-02-20 오후 10 36 01" src="https://user-images.githubusercontent.com/48906747/74942007-5be6ac80-5437-11ea-8d84-36623870d07c.png">
<img width="1126" alt="스크린샷 2020-02-20 오후 10 46 32" src="https://user-images.githubusercontent.com/48906747/74942013-6012ca00-5437-11ea-9562-c8eb4291090f.png">
<img width="1126" alt="스크린샷 2020-02-20 오후 10 36 50" src="https://user-images.githubusercontent.com/48906747/74942009-5e490680-5437-11ea-9547-abdfa736fc96.png">

- 어카운트 생성 후 이용가능
- 현재 세션 > 드래그 하여 그룹핑 가능 
- 컬렉션 / 그룹컬렉션(organization) 가능
- 현재 세션 저장시 세션 종료 경고알림 (한번만 뜨는듯)
- 메모, 노트, 북마크 상세히 가능 
- 컬렉션 별 공유 가능 (팀원 초대 가능)
- 검색가능 
——
구글리뷰: 원탭과 달리 계정으로 브라우저 별 싱크도 된다고 함 
새로운 탭 생성시 toby가 우선적으로 뜨는 점 수정 요청 있음 

**<One- Tap (별4.5, 12,506/2,149,178)>**
- 저장한 세션을 타임라인으로 보여줌 
- 축약되며 세션 종료됨 
- 직관적
——
구글리뷰: 크롬 업데이트 될때마다 날아간다?
유저들이 단축키 열망함(있는데 잘 모르나봄)

여러가지 찾아본 결과, 세션버디가 가장 리뷰 많은 앱,  토비가 가장 완성도 있는 앱으로 보임
세션버디의 지난 기록 열람이 흥미로웠음. 토비 같은 경우엔 Axiom zen이라는 곳에서 만들었는데, 
구글 페북 등등이 쓴다고 함

**Comment by worldwideGW** [comment]
@suath 
토비랑 세션버디 저도 한 번 사용해볼게요! 읽어보니까 수아님 말대로 완성도가 높아보여용 bb

**Comment by worldwideGW** [comment]
벤치마킹
1. surfit.io(서비스기획 및 UX/UI 정보 큐레이팅 익스텐션 서비스)

**장점**
1. 원탭과 비교했을 때, 디자인이 깔끔하고 이쁘다(서비스 신뢰도가 높음)
2. History를 누르면 여태껏 내가 클릭한 사이트들을 카드형태로 제시해준다.
    :  카드형태로 제시하면 내가 어떤 게시물을 읽었었는지 리마인드 하기가 쉽다는 장점이있다.
    :  원탭이 방문기록을 한 줄로 보여주는 것에 대한 보완이 될 수 있다고 판단.

**단점**
1. 히스토리 카드 한 유닛이 너무 커서 기록이 많이 쌓일수록, 아래에 있는 정보까지 접근하기 어렵다.
2. 방문기록을 내가 편집하기 어렵다.
    : 방문기록을 카테고리를 만들어 분류하거나 삭제하는 등 편집기능은 제공하지 않고 있어 우리 서 
     비스의 차별점이 될 수 있다고 생각됩니다.

![image](https://user-images.githubusercontent.com/59359556/74945317-dfee6380-543a-11ea-92d7-cacb41785422.png)

**Comment by worldwideGW** [comment]
@suath 

토비 사용해보니까 저희가 구상하려는 서비스랑 거의 똑같아서 어떤 차별점을 두어야할지 모르겠네요.. ;; 계속 사용해보면서 차별점은 어떤부분이 있을지 검토해보겠습니다.

![image](https://user-images.githubusercontent.com/59359556/74956443-71fd6880-5449-11ea-8a54-bfb294c3bacc.png)
