### ISSUE TITLE
URLink #3 플로우차트 설계

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#11]

**Comment by worldwideGW** [comment]
방문한 웹사이트 보여주는 메인페이지 시안1

![1안 – 2](https://user-images.githubusercontent.com/59359556/74745736-a507f680-52a7-11ea-88f1-be4ff160b550.png)


![1안](https://user-images.githubusercontent.com/59359556/74745744-a802e700-52a7-11ea-8edb-9b8786d46289.png)

**Comment by suath** [comment]
![IMG_0126](https://user-images.githubusercontent.com/48906747/74960902-85600200-5450-11ea-9be8-ce522844ab31.png)

- 원탭의 레이아웃을 최대한 살려야 한다고 생각함(익숙함을 위해). 탭 기록 시 겹겹의 레이어가 ‘축약’된다는 후련함이 기본.

**Comment by worldwideGW** [comment]
**플로우차트**
https://www.draw.io/#G1tuFVwRW2mfGXU0kMxGY2sr0A95S3WOzN

수시로 확인하고 피드백 부탁드려요
