### ISSUE TITLE
마이 데일리 포트폴리오 아이디어 구체화

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#2]
아이디어 구체화를 위해 제약없이 다양한 방법으로 조사해주세요.

**필수**
1. 위 아이디어 관련 비슷한 서비스 찾기

2. 관련 API 탐색 후 사용 가능 여부 확인

3. 자신이 그걸 사용했을 때, 구체적으로 어떤 기능이 필요하고, 어떤 상황에 사용할 것 같은지 생각해보기

**Comment by worldwideGW** [comment]
**마이데일리포트폴리오 아이디에이션**

### **서비스 정의**

마이데일리포트폴리오 : 여러 곳에 흩어진 포트폴리오를 통합 관리하는 서비스

****Q. 에버노트, 노션에 비해 어떤 차별점이 있는지 발견하기 어려웠어요**

### 서비스 목적

이 서비스를 통해 나의 포트폴리오를 더욱 잘 관리하게 되어야 한다.

포트폴리오를 더 잘 관리할 수 있는 가이드를 주어야 한다.

포트폴리오 관리의 목적은 취업 또는 타인의 인정을 받기 위해서이다.

### 데스크 리서치

[https://m.post.naver.com/viewer/postView.nhn?volumeNo=27382330&memberNo=12244919&vType=VERTICAL](https://m.post.naver.com/viewer/postView.nhn?volumeNo=27382330&memberNo=12244919&vType=VERTICAL)

공채가 줄어들고 수시채용이 확대되는 추세입니다. 개발자, 디자이너 뿐만 아니라, 다양한 취준생들은 자신의 활동과 결과물을 세상에 보여주고 자신을 표현해야하는 상황에 놓여있습니다.

### 문제 정의

포트폴리오를 관리하면서 생기는 문제에는 어떤 것들이 있을까?

포트폴리오를 관리하는 이유는 내가 회사에 매력적인 사람으로 보이기 위함

### 최종 사용자

최종 사용자는 누가 될 것인가?

개발자, 디자이너 말고도 마케터 등 포트폴리오가 없는 사람들도 필요하지 않을까?

### **해결할 이슈**

1. 한 곳에서 나의 포트폴리오를 통합 관리하는게 어떤 가치가 있을까?
2. 작업물의 성격에(코드, 디자인) 따라서 지원하는 화면 및 방법이 달라야 하는데, 다양한 니즈를 충족시킬 수 있을까? 

### **레퍼런스 조사**

**1. 노션**

**장점** 

-노션은 게시글을 쓸 수 있는 다양한 서비스 제공, 사진, 동영상 등 다양한 포맷을 지원한다.

-자유도가 엄청 높아 원하는대로 편집이 가능하다.

**단점**

-너무 자유도가 높아, 원하는 대로 편집하기가 어려워 포기하게 된다.

-쓰는 기능만 사용하게 된다. 오히려 손이 잘 가지 않는다.

-학습하는데 시간이 오래 걸리고, 혼자 학습하기가 어렵다.

**2. 크리에이터링크**

[https://creatorlink.net/](https://creatorlink.net/)

코딩을 하지 않더라도, 주어진 템플릿 블록을 쌓아나가며 자신에게 적합한 형태의 웹사이트를 무료로 만들 수 있는 사이트

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ffb22e86-73c9-4ae6-a9e5-d7881ec6cee4/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/ffb22e86-73c9-4ae6-a9e5-d7881ec6cee4/Untitled.png)

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/70f8106e-3775-47e6-a557-4e6ec37597f2/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/70f8106e-3775-47e6-a557-4e6ec37597f2/Untitled.png)

**장점**

대시보드와 방문자 통계를 지원하여,  웹사이트 제작 뿐만 아니라 관리를 효과적으로 도와줍니다.

다양한 템플릿이 지원되어, 손쉽게 자신이 원하는 대로 사이트를 제작할 수 있다.

**단점**

템플릿이 주어져 있지만, 만드는 과정에서 시간이 많이 든다.

사진 및 게시글 업로드가 낯설고 불편하다.

### **총평**

### 노션, 크리에이터링크 등의 서비스는 공통적으로 웹사이트의 구조를 구축하는데 시간과 노력이 많이 필요했고 어려웠습니다.

마이데일리포트폴리오가 노션, 에버노트와 같은 서비스로 경쟁하면 질 수 밖에 없습니다. 기존의 플랫폼에 게시물을 더 잘 올려줄 수 있으며, 쉽게 관리할 수 있는 방향으로 포지셔닝해야 합니다.

마이데일리포트폴리오는 웹사이트 구축과 업로드 기능에 초점을 맞추기 보다는 포트폴리오를 관리하기 쉽게, 공유 및 발견하기 쉽도록 만드는게 중요하다는 생각이 들었습니다.

### 서비스의 차별점 정의

기존 포트폴리오 사이트를 등록하고 관리하는 기능에 초점을 맞추자!

### **서비스의 핵심 기능 정의**

기존 포트폴리오 사이트를 등록하고 관리하는 기능에 초점을 맞추었다.

1. **다양한 포트폴리오 사이트 등록 및 불러오기 기능**

  - 각 포폴 사이트 별, 사용자 유입 및 통계를 확인할 수 있다.(좋아요, 댓글 갯수 or 유입경로)

 **2. 나의 활동 기록을 타인에게 보여줄 수 있다.**

 **3. 자신의 포트폴리오 사이트 별 우선순위를 등록하고 편집할 수 있다.**

     ex) 개발자는 1순위 github, 2순위 tistory, 디자이너는 1순위 behance, 2순위 instagram으로 태그           

          나 카테고리로 우선도가 높은 사이트 설정가능

**4. 포트폴리오 별 초고를 작성할 수 있는 보드를 만들어 제공한다.**

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/2ded051c-15f2-4629-a195-06a9038a4459/1.jpg](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/2ded051c-15f2-4629-a195-06a9038a4459/1.jpg)

**5. 대시보드를 제공할 수 있다.**

**6. 직군별 포폴 관리하는 법에 대한 글을 큐레이팅하여 제시**

**7. 활동을 잘하고 있는 유저를 노출시켜줄 수 있다.**

깃허브를 매력적으로 꾸미는 법 [https://sujinlee.me/professional-github/](https://sujinlee.me/professional-github/)

**Comment by suath** [comment]
**해결할 이슈**
1. 한 곳에서 나의 포트폴리오를 통합 관리하는게 어떤 가치가 있을까?

- 주로 사용하는 채널이 무엇인지 + 관리의 불편함이 어떤식으로 있는지 구체적으로 궁금
(깃허브, 티스토리, 이렇게 두개라면 따로 대시보드를 만드는 것이 정리를 위한 정리가 되는 것은 아닌지?!!)
- 개인적으로 첨에 슬랙에서 구글갔다 깃갔다 하는게 귀찮아서, 한번에 볼 수 있음 편하겠다 정도로 아이디어를 이해했는데.. 그렇게 되면 적어도 저한테는 가치가 있을거 같습니다..

2. 작업물의 성격에(코드, 디자인) 따라서 지원하는 화면 및 방법이 달라야 하는데, 다양한 니즈를 충족시킬 수 있을까?

- 디자이너의 경우 '포트폴리오'라면 정제된 완성본을 사이트에 보여주는 식이라 개인파일의 버전관리가 가장 크고, 개인 웹, 각종 포폴 사이트에 업로드 하는 정도. 커뮤니티 사이트들은 사이트 별로 업로드 형식이 정제화되어 있음. 디자이너의 경우 초고 대시보드를 만들기 애매하지 않을까 싶음? 

![노트폴리오](https://blogfiles.pstatic.net/MjAyMDAyMTVfNjIg/MDAxNTgxNzIwMTE1NTg3.4DHeBt40qdz6ja7QWskimLdNie3WUetTE9HJ0Xk_6qsg.y9pFbXOK2fXJbITe9i4oM_GhHuDx5_BkgMhBTyO8Zq4g.PNG.kimsuaqu/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2020-02-15_%EC%98%A4%EC%A0%84_7.38.37.png)
![비핸스](https://blogfiles.pstatic.net/MjAyMDAyMTVfMjQ0/MDAxNTgxNzIwMTE1Njk2.8VxDaPcHDgEBzmckzt2gfvTTBLh14wySdsSK3fI8N6gg.PP9W6wtchSzBa0qS9EZYN7nfiDaRgb_9Z7FRquTSM4Mg.PNG.kimsuaqu/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7_2020-02-15_%EC%98%A4%EC%A0%84_7.39.24.png)

3. '데일리'에 더 초점을 맞춰보면 어떨까요

- 깃허브 1일1커밋 잔디심기가 아주 매력적인 것 같음. 그걸 확장해보면 어떨까.. 혹 직접적인 관리를 통합하기가 어렵다면, 매일의 과업에 동기부여를 할 수 있는 방향으로. 했는지 안했는지만 제대로 체크하고 독려해줄 수 있다면? 

https://brunch.co.kr/@aria-grande/27
- 크루를 모집해서 100일간 같이 잔디를 심는 프로젝트를 했다는 내용
- 100일간 커밋 독려하고 '슬랙'에 인증글 올리는 일일 매니저를 돌아가면서 했다고 함
- 출석체크매니저가 그날 현황을 '구글 독스'에 올렸다고 함 

스스로도, 더 나아가 팀으로도, 매니저 없이 할 수 있으면 좋겠다. 이번에 데일리 디자인 스터디를 하는데, 모임에서 출첵이나 패널티 논의하기가 상당히 어려웠음.

'마이 데일리 프로젝트 매니저' 느낌?? '포트폴리오'라면 개인마다 최종 목적이 상이해서, 공유단계까지 간다면 링크드인 같은 형식이 되지 않을까 싶은데, 데일리 프로젝트로 한정한다면 더 재미있을것 같음.

---
통합관리

https://ezposting.co.kr/
SNS 통합관리, SNS채널에 포스팅할 글을 등록 후 한 번에 여러 개의 채널에 포스팅 작업

https://try.wrike.com/google-project-management/
구글 태스크 매니저 

https://blog.proofhub.com/11-best-project-management-apps-for-business-in-2019-dca9617bf114
프로젝트 매니징 앱 리스트

**Comment by Chohongjae** [comment]
2. 관련 API 탐색 후 사용 가능 여부 확인

- 깃허브 : http://developer.github.com/v 3/actions/work flows/ - 사용 안 해봐서 문서를 조금 더 봐야 할듯함.
- 구글드라이브 : http://developers.google.com/drive/API/v 3/about-SDK - 다른 구글 API들을 사용해본 경험이 있음(gA, you tube, sheet 등등) 비슷하게 앱 생성하고 권한 받아서 사용하는 형태라 어렵지 않을듯함. API로 어디까지 가능한지를 살펴보아야 함.
- 아이클라우드 : http://reincubate.com/KO/support/iCloud/icloud-API-v1/#working-with-the-API - 문서만 봐서는 어디까지 제공하는 것인지 잘 모르겠음
- 삼성클라우드 : 관련된 기능이 없는 듯??
- 에버노트 : http://dev.evernote.com/doc/

3. 자신이 그걸 사용했을 때, 구체적으로 어떤 기능이 필요하고, 어떤 상황에 사용할 것 같은지 생각해보기

내가 사용한다면, 에버노트처럼 문서기록관리(?)의 방향인지, 클라우드 통합 관리인지에 따라 달라질듯 함.
혹은 서비스 안에서 문서관리도 되고, 클라우드 통합 관리도 될지??
오버플로 나지 않게 적절히 기능을 쳐내야 할듯..
문서기록이 목적이 된다면 에버노트를 사용했을 때 UX 적으로 불편했던 적이 많아서
편리한 에버노트가 되어야 할 것인지?
클라우드 통합 관리가 된다면 클라우드 대시보드가 돼서 CRUD가 된다면 편리할듯함..
수정할 수 있는 링크만 제공되어도 편리할까?
UX가 나와봐야 판단이 가능할듯함

**Comment by worldwideGW** [comment]
수아님 의견에 대해 공감합니당
제 생각도 덧붙여 놓았어요.

> 1. '데일리'에 더 초점을 맞춰보면 어떨까요
> 
> * 깃허브 1일1커밋 잔디심기가 아주 매력적인 것 같음. 그걸 확장해보면 어떨까.. 혹 직접적인 관리를 통합하기가 어렵다면, 매일의 과업에 동기부여를 할 수 있는 방향으로. 했는지 안했는지만 제대로 체크하고 독려해줄 수 있다면?
> 
> https://brunch.co.kr/@aria-grande/27
> 
> * 크루를 모집해서 100일간 같이 잔디를 심는 프로젝트를 했다는 내용
> * 100일간 커밋 독려하고 '슬랙'에 인증글 올리는 일일 매니저를 돌아가면서 했다고 함
> * 출석체크매니저가 그날 현황을 '구글 독스'에 올렸다고 함
> 
> 스스로도, 더 나아가 팀으로도, 매니저 없이 할 수 있으면 좋겠다. 이번에 데일리 디자인 스터디를 하는데, 모임에서 출첵이나 패널티 논의하기가 상당히 어려웠음. 개인적으로 꾸준히 매일 글쓰기 모임하고 있는데, 참여 현황 파악하는게 큰 과업이다보니 결국 패널티 난장판됌
> 
> **'마이 데일리 프로젝트 매니저' 느낌?? '포트폴리오'라면 개인마다 최종 목적이 상이해서, 공유단계까지 간다면 링크드인 같은 형식이 되지 않을까 싶은데, 데일리 프로젝트로 한정한다면 더 재미있을것 같음.
>** 

**저도 이 방향성이 개발자를 넘어 디자이너와 모든 프로젝트를 하는 사람들에게 적합하다고 생각해요. 
작업물의 성격과 상관없이 모든 프로젝트에 적용이 가능해서요!
"프로젝트 출결 관리나, 깃허브의 1일 1커밋 독려 등 여러 측면에서 프로젝트를 쉽게 관리해주는 서비스에 초점을 맞춰보는 것도 좋은 것 같아요!**

-

**Comment by suath** [comment]
PM의 생산성을 '업'시켜줄 프로젝트 관리 툴 15선
http://www.rcy.co.kr/xeb/10922

대부분 드라이브 연동이 된다고 써있어서 파일트래킹이 되는건가 싶었는데
...
