### ISSUE TITLE
다른 아이템(아이디어) 생각해오기

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#3]
마이 데일리 포트폴리오 외에 다른 아이템에 대해 생각해봅시다!

평소에 하고싶었거나, 겪었던 문제를 해결할 수 있는 아이디어를 자유롭게 조사해주세요!
기술적인 제약은 제쳐두고, 다양한 아이디어를 폭넓게 생각해오시면 좋을 것 같습니다!

아자!

**Comment by worldwideGW** [comment]
**다른 서비스 아이디어 조사하기**
원문 : https://www.notion.so/vvidstudio/8fe945e22dbf4ba78a149cc83e691701

### 아이디어 1. 칼로리 체크

매일 먹는 음식의 칼로리를 입력하고 눈으로 볼 수 있게 해주어, 건강한 식단관리, 체중관리를 돕는다. 총 칼로리 뿐만 아니라, 당 섭취정도, 나트륨 섭취정도 까지 조사할 수 있다. 

### 아이디어2. 직장인들이 퇴근하고 남은시간을 잘 활용할 수 있게 도와주는 휴식플래너

상황 : 주 52시간 근무가 바꾼 "저녁이 있는 삶"

[https://www.20slab.org/Archives/35061](https://www.20slab.org/Archives/35061)

제약조건 : 출근시간과 퇴근시간을 제외한 나머지 시간만 계획할 수 있다.

니즈 : 퇴근하고 나머지 시간을 알차게 보낼 수는 없을까?

문제 : 하지만 알차게 보내지 못하고 있다.

어떻게 하면 이 문제를 해결할 수 있을까?

일침을 통해 흘러가는 시간의 가치를 느끼게 해주자.

### 아이디어3. 반려동물 입양센터 지도맵 제시

[https://www.trendmonitor.co.kr/tmweb/trend/allTrend/detail.do?bIdx=1842&code=0404&trendType=CKOREA](https://www.trendmonitor.co.kr/tmweb/trend/allTrend/detail.do?bIdx=1842&code=0404&trendType=CKOREA)

반려동물을 키우려는 인식이 증가하고 있다

반려동물을 키울 수 있는 사이트를 알려주는 서비스

### 아이디어4. 유기동물(고양이, 강아지 등) 제보 웹사이트

길에 돌아다니는 고양이, 강아지 사진을 찍어 업로드하여 주인을 찾을 수 있도록 하는 사이트

: 이미 사이트 존재

### 아이디어5. 요일별로 내가 구독받고 싶은 정보를 전달 받는 사이트.

ex) 월요일에는 기획에 대한 정보만, 화요일에는 스타트업소식에 대한 정보만 선택 알림해주는 서비스

기존 문제 : 다양한 정보를 큐레이팅 받고 있지만, 정작 잃지 않고 버려지는 정보가 많았다.

해결방안 : 정보의 종류에 따라 받아보는 요일을 내가 정할 수 있다면, 버려지는 정보의 양을 줄일 수 있지 않을까?

차별점 : 기존의 큐레이팅 서비스는 다양한 정보를 노출시켜주지만, 요일별로 받아볼 수 있는 서비스는 없었다.  

### 아이디어6. 타투샵 모아서 알려주는 웹사이트

### 아이디어7. 치매를 검진하고 예방하는 웹사이트

치매예방게임, 관련정보를 제공하는 웹사이트

### 아이디어8. 노인소외문제 해결하는 플랫폼

노인들이 웹을 쉽게 쓸 수 있는가?

**Comment by Chohongjae** [comment]
아이디어1. 지도에 여행을 기록하는 웹사이트
나의 여행기록 관리와 다른 사람의 여행내역을 관찰할 수 있음.

**Comment by leesoo7595** [comment]
### 아이디어1. 카테고리별 블로그 플랫폼

1. 카테고리 별 블로그 조회
2. 구독 가능, 알람 가능
3. 현재 접속자 기준 채팅방 구성
4. 그 외 추가적인 기능 지속적으로 추가
5. 댓글 기능 등

* 해당 아이디어를 선정한 이유

실력적으로나 실험적으로나 구현해보기 좋은 주제라고 생각한다. 
또한 현재 존재하는 블로그 플랫폼에서 좀 더 발전된 기능을 충분히 구현가능할 수 있다.(의지가 있다면)
기능화, 활용성이 좀 더 높아질 수 있다.(의지가 있다면)

**Comment by worldwideGW** [comment]
### **이수's Idea**

**도메인을 따와서 아마존은 아마존별로, 브런치는 브런치별로 모아주는 원탭과 유사한 서비스를 만들면 어떨까?**

**<기능정의>**

-방문로그 추적 기능

-도메인 별로 사이트 자동분류

-자주가는 사이트 노출

-대시보드로 나의 활동 통계 확인가능

-방문통계 바탕으로 사이트 추천가능.(필터링, 딥러닝 X)

-할 일 : [개발]원탭이 어떤 코드로 돌아가는지 알아야 함.

           : [기획]정말 사용성이 있는지, 

니즈 :  내가 어떤 사이트를 방문했는지 알고 싶다

           내가 방문했던 사이트가 어떤거였는지 확인하고 싶다.

           창이 많아지면, 보기에 불편하고 찾기에 불편하다. 

           레퍼런스 찾고, 정보를 리서치할때 편하게 볼 수 있다

           **리서치 필수 템** 

           **카테고리별로 모아야 한다.**

우리만의 차별점

-방문로그 추적 기능

-도메인 별로 사이트 자동분류

-자주가는 사이트 노출

-대시보드로 나의 활동 통계 확인가능

**Comment by leesoo7595** [comment]
+ 비회원/회원간의 차별성

회원가입을 했을 때, 해당 url 관리를 DB로 해줌 / 비회원의 경우 localstorage로 관리
-> 다른 기기로 해당 url 리스트 조회 가능

**Comment by anxiubin** [comment]
크롬 익스텐션 만들기
https://www.letmecompile.com/chrome-extension-with-react/
https://beenlife.tistory.com/4
https://developer.chrome.com/extensions/getstarted
