### ISSUE TITLE
IDEA_01_[공통] 1안 화면 브레인스토밍 [뷰]을 위한 리서치하기

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#8]

**Comment by suath** [comment]
![IMG_0127](https://user-images.githubusercontent.com/48906747/74975839-0b894200-546b-11ea-8dde-cbbd8f445382.png)

**Comment by worldwideGW** [comment]
@suath 

컨셉1의 프로젝트 초기 설정 단계는 클라우드 변화를 트래킹하거나, 폴더를 기준으로 보여주는 방법은 너무 어려울 것 같아요. 파일 3개를 올려도 프로젝트 팀원들이 보기에 계획이 완성되지 않았다고 얘기할 수도 있고, 파일의 내용이 매우 부실한데 파일을 업로드 하는 것만으로 평가하기 어려움

대안 : 팀장이 스스로, 또는 팀원들과 협의하에 매일의 과업의 완성도를 보고 받아들일지 말지 결정하는 방식을 도입하면 어떨까요?
깃허브의 마일스톤은 팀장 또는 팀원이 해당 프로젝트가 완성도가 높다고 판단할 경우, close버튼을 눌러 해당 과업을 종료하고, 그것이 퍼센테이지에 반영됨. (과업 5개중 2개 close 시, 2/5가 되어 40%로 자동갱신됩니다.)
