### ISSUE TITLE
IDEA_01_[공통] 1안과 비슷한 서비스 벤치마킹 및 사용해보기

### ISSUE THREAD

**Issue by worldwideGW** [YAPP-16th/Team_Web_1_Client#9]

**Comment by suath** [comment]
PM의 생산성을 '업'시켜줄 프로젝트 관리 툴 15선
http://www.rcy.co.kr/xeb/10922

대부분 드라이브 연동이 된다고 써있어서 파일트래킹이 되는건가 싶었는데
안되는거 같음 
대시보드 만든다면 참고점은 많을듯
